//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;

public class Main extends JPanel implements ActionListener{
    ArrayList<Word> loadedWords = new ArrayList<Word>();
    Word[] words = new Word[10];
    private JLabel jcomp1;
    private JTextField jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JTextField jcomp5;
    private JTextField jcomp6;
    private JTextField jcomp7;
    private JTextField jcomp8;
    private JTextField jcomp9;
    private JTextField jcomp10;
    private JTextField jcomp11;
    private JTextField jcomp12;
    private JTextField jcomp13;
    private JLabel jcomp14;
    private JLabel jcomp15;
    private JLabel jcomp16;
    private JLabel jcomp17;
    private JLabel jcomp18;
    private JLabel jcomp19;
    private JLabel jcomp20;
    private JLabel jcomp21;
    private JLabel jcomp22;
    private JLabel jcomp23;
    private JLabel jcomp24;
    private JLabel jcomp25;
    private JLabel jcomp26;
    private JLabel jcomp27;
    private JLabel jcomp28;
    private JLabel jcomp29;
    private JLabel jcomp30;
    private JButton jcomp31;
    private JButton jcomp32;
    private JLabel jcomp33;

    public Main() {


        //construct components
        jcomp1 = new JLabel ("newLabel");
        jcomp2 = new JTextField (5);
        jcomp3 = new JLabel ("...");
        jcomp4 = new JLabel ("newLabel");
        jcomp5 = new JTextField (5);
        jcomp6 = new JTextField (5);
        jcomp7 = new JTextField (5);
        jcomp8 = new JTextField (5);
        jcomp9 = new JTextField (5);
        jcomp10 = new JTextField (5);
        jcomp11 = new JTextField (5);
        jcomp12 = new JTextField (5);
        jcomp13 = new JTextField (5);
        jcomp14 = new JLabel ("newLabel");
        jcomp15 = new JLabel ("newLabel");
        jcomp16 = new JLabel ("newLabel");
        jcomp17 = new JLabel ("newLabel");
        jcomp18 = new JLabel ("newLabel");
        jcomp19 = new JLabel ("newLabel");
        jcomp20 = new JLabel ("newLabel");
        jcomp21 = new JLabel ("newLabel");
        jcomp22 = new JLabel ("...");
        jcomp23 = new JLabel ("...");
        jcomp24 = new JLabel ("...");
        jcomp25 = new JLabel ("...");
        jcomp26 = new JLabel ("...");
        jcomp27 = new JLabel ("...");
        jcomp28 = new JLabel ("...");
        jcomp29 = new JLabel ("...");
        jcomp30 = new JLabel ("...");
        jcomp31 = new JButton ("check");
        jcomp32 = new JButton ("next");
        jcomp33 = new JLabel ("q");

        jcomp31.addActionListener(this);
        jcomp32.addActionListener(this);

        //adjust size and set layout
        setPreferredSize (new Dimension (459, 448));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);
        add (jcomp17);
        add (jcomp18);
        add (jcomp19);
        add (jcomp20);
        add (jcomp21);
        add (jcomp22);
        add (jcomp23);
        add (jcomp24);
        add (jcomp25);
        add (jcomp26);
        add (jcomp27);
        add (jcomp28);
        add (jcomp29);
        add (jcomp30);
        add (jcomp31);
        add (jcomp32);
        add (jcomp33);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (30, 30, 100, 25);
        jcomp2.setBounds (135, 30, 160, 25);
        jcomp3.setBounds (330, 30, 100, 25);
        jcomp4.setBounds (30, 60, 100, 25);
        jcomp5.setBounds (135, 60, 160, 25);
        jcomp6.setBounds (135, 95, 160, 25);
        jcomp7.setBounds (135, 130, 160, 25);
        jcomp8.setBounds (135, 165, 160, 25);
        jcomp9.setBounds (135, 205, 160, 25);
        jcomp10.setBounds (135, 245, 160, 25);
        jcomp11.setBounds (135, 280, 160, 25);
        jcomp12.setBounds (135, 315, 160, 25);
        jcomp13.setBounds (135, 350, 160, 25);
        jcomp14.setBounds (30, 95, 100, 25);
        jcomp15.setBounds (30, 130, 100, 25);
        jcomp16.setBounds (30, 165, 100, 25);
        jcomp17.setBounds (30, 205, 100, 25);
        jcomp18.setBounds (30, 245, 100, 25);
        jcomp19.setBounds (30, 280, 100, 25);
        jcomp20.setBounds (30, 315, 100, 25);
        jcomp21.setBounds (30, 350, 100, 25);
        jcomp22.setBounds (330, 60, 100, 25);
        jcomp23.setBounds (330, 95, 100, 25);
        jcomp24.setBounds (330, 130, 100, 25);
        jcomp25.setBounds (330, 165, 100, 25);
        jcomp26.setBounds (330, 205, 100, 25);
        jcomp27.setBounds (330, 240, 100, 25);
        jcomp28.setBounds (330, 280, 100, 25);
        jcomp29.setBounds (330, 315, 100, 25);
        jcomp30.setBounds (325, 350, 100, 25);
        jcomp31.setBounds (215, 400, 100, 25);
        jcomp32.setBounds (340, 400, 100, 25);
        jcomp33.setBounds (350, 5, 100, 25);

        loadWords("res/words.txt");
        randomizeArray();
        setWords();
    }
    public void setWords(){
        jcomp1.setText(words[0].getMainWord());
        jcomp4.setText(words[1].getMainWord());
        //14-21
        jcomp14.setText(words[2].getMainWord());
        jcomp15.setText(words[3].getMainWord());
        jcomp16.setText(words[4].getMainWord());
        jcomp17.setText(words[5].getMainWord());
        jcomp18.setText(words[6].getMainWord());
        jcomp19.setText(words[7].getMainWord());
        jcomp20.setText(words[8].getMainWord());
        jcomp21.setText(words[9].getMainWord());
    }
    public String[] retrieveAnswers(){
        String[] a = new String[10];
        a[0] = jcomp2.getText();
        a[1] = jcomp5.getText();
        a[2] = jcomp6.getText();
        a[3] = jcomp7.getText();
        a[4] = jcomp8.getText();
        a[5] = jcomp9.getText();
        a[6] = jcomp10.getText();
        a[7] = jcomp11.getText();
        a[8] = jcomp12.getText();
        a[9] = jcomp13.getText();
        return a;
    }
    public void randomizeArray(){
        for(int i=0;i<words.length;i++){
            words[i] = loadedWords.get((int)(Math.random()*loadedWords.size()));
        }
    }
    public void loadWords(String path){
        try {
            BufferedReader reader = new BufferedReader(new FileReader(new File(path)));
            String a = "";
            while ((a=reader.readLine())!=null){
                loadedWords.add(new Word(a.split("=")[0],a.split("=")[1]));
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public void checkAnswersAndWriteResults(String[] arg){
        String[] out = new String[arg.length];
        int score = 0;
        for(int i=0;i<out.length;i++){
            if(words[i].compare(arg[i])) {
                out[i] = words[i].getAnswer() + " V";
                score++;
            }else{
                out[i] = words[i].getAnswer() + " X";
            }
        }
        jcomp33.setText(score+"/10");
        writeBackAnswers(out);
    }
    public void writeBackAnswers(String[] arg){
        jcomp3.setText(arg[0]);
        jcomp22.setText(arg[1]);
        jcomp23.setText(arg[2]);
        jcomp24.setText(arg[3]);
        jcomp25.setText(arg[4]);
        jcomp26.setText(arg[5]);
        jcomp27.setText(arg[6]);
        jcomp28.setText(arg[7]);
        jcomp29.setText(arg[8]);
        jcomp30.setText(arg[9]);
    }
    public void resetAnswers(){
        jcomp3.setText("...");
        jcomp22.setText("...");
        jcomp23.setText("...");
        jcomp24.setText("...");
        jcomp25.setText("...");
        jcomp26.setText("...");
        jcomp27.setText("...");
        jcomp28.setText("...");
        jcomp29.setText("...");
        jcomp30.setText("...");

        jcomp2.setText("");
        jcomp5.setText("");
        jcomp6.setText("");
        jcomp7.setText("");
        jcomp8.setText("");
        jcomp9.setText("");
        jcomp10.setText("");
        jcomp11.setText("");
        jcomp12.setText("");
        jcomp13.setText("");

        jcomp33.setText("");
    }

    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Main());
        frame.pack();
        frame.setVisible (true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==jcomp32){//Next
            resetAnswers();
            randomizeArray();
            setWords();
        }else if(e.getSource()==jcomp31){//Check
            checkAnswersAndWriteResults(retrieveAnswers());
        }
    }
}
